% Depends on having m2html in your path!
% See
%   http://www.artefact.tk/software/matlab/m2html/doc/
% 
%   https://devanginiblog.wordpress.com/2015/11/16/how-to-properly-document-matlab-code/

m2html('mFiles', 'ctap'...
     , 'htmlDir', fullfile('..', 'ctap-docs')...
     , 'recursive', 'on'...
     , 'source', 'off'...
     , 'todo', 'on')