name: Sync to GitLab

on:
  push:
    branches:
      - main       # Change to your default branch if different
      - master     # Include if you use this branch name
      # Add other branches you want to sync

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      
      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_REPO_URL: ${{ secrets.GITLAB_REPO_URL }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Add GitLab remote using token for authentication
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@${GITLAB_REPO_URL#https://}
          
          # Get the branch name from the push event
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          
          # Push to GitLab
          git push gitlab ${BRANCH_NAME}:${BRANCH_NAME} --force
